### ISSUE TITLE
Message panel and tooltips can't be read in dark mode

### ISSUE THREAD

**Issue by lightbulbjim** [bryceco/nethack-cocoa#28]
Hi, I've noticed that the background colour of the message panel and tooltips are set statically. This means that the text cannot be read when in dark mode.

Light mode:
<img width="948" alt="Screenshot 2021-08-03 at 09 11 28" src="https://user-images.githubusercontent.com/4312404/127937822-b61a55a1-8c38-411c-b4aa-d88743962603.png">

Dark mode:
<img width="947" alt="Screenshot 2021-08-03 at 09 11 45" src="https://user-images.githubusercontent.com/4312404/127938058-742411d2-5650-4568-9e98-c0b4195ab6dc.png">

The fix would be to make the background of the message panel and tooltips dark when in dark mode. I would be happy to send a PR but I'm not sure how to get the Cocoa port to build - any pointers would be appreciated.

I'm running NetHackCocoa 3.6.6 (3660) on macOS 11.5.1.

**Comment by lightbulbjim** [comment]
This also applies to the character creation window:
<img width="410" alt="Screenshot 2021-08-03 at 20 45 35" src="https://user-images.githubusercontent.com/4312404/128003238-bca6f5b9-1c45-4a3f-9d3d-adc2e99bab64.png">

**Comment by bryceco** [comment]
Fixed in dfbb427e9d9a6687764b1c31b9d418ef9a171275
